### ISSUE TITLE
Dialog is created with an invalid context

### ISSUE THREAD

**Issue by ollide** [ollide/Xposed-InstaLikeSettings#1]
When you trigger the like dialog right after publishing an image, the app crashes.

```
FATAL EXCEPTION: main
Process: com.instagram.android, PID: 5572
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@2bad541e is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:562)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:272)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
at android.app.Dialog.show(Dialog.java:298)
at org.ollide.xposed.instagram.MethodHooks.showLikeDialog(MethodHooks.java:122)
at org.ollide.xposed.instagram.MethodHooks.access$300(MethodHooks.java:24)
at org.ollide.xposed.instagram.MethodHooks$3.replaceHookedMethod(MethodHooks.java:99)
at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:15)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:635)
at com.instagram.android.feed.a.b.af.onClick(Unknown Source)
```

**Comment by ollide** [comment]
Fixed in 1.2
